name: OCaml
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: ./tools/ci/actions/actions.sh
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_RANGE: ${{ toJson(github.event) }}
